<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\ProductToAddress $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="product-to-address-form">

    <?php $form = ActiveForm::begin([
    'id' => 'ProductToAddress',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute id -->
			<?= $form->field($model, 'id')->textInput() ?>

<!-- attribute address_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
    $form->field($model, 'address_id')->widget(\kartik\select2\Select2::classname(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'address_id',
        'data' => \yii\helpers\ArrayHelper::map(app\models\Address::find()->all(), 'id', 'label'),
        'options' => [
            'placeholder' => Yii::t('cruds', 'Type to autocomplete'),
            'multiple' => false,
            'disabled' => (isset($relAttributes) && isset($relAttributes['address_id'])),
        ]
    ]); ?>

<!-- attribute product_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
    $form->field($model, 'product_id')->widget(\kartik\select2\Select2::classname(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'product_id',
        'data' => \yii\helpers\ArrayHelper::map(app\models\Product::find()->all(), 'id', 'label'),
        'options' => [
            'placeholder' => Yii::t('cruds', 'Type to autocomplete'),
            'multiple' => false,
            'disabled' => (isset($relAttributes) && isset($relAttributes['product_id'])),
        ]
    ]); ?>

<!-- attribute quantity -->
			<?= $form->field($model, 'quantity')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'ProductToAddress'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('cruds', 'Create') : Yii::t('cruds', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

