<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\ProductToAddress $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('models', 'Product To Address');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models', 'Product To Addresses'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="giiant-crud product-to-address-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('models', 'Product To Address') ?>
        <small>
            <?= $model->id ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('cruds', 'Edit'),
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('cruds', 'Copy'),
            ['create', 'id' => $model->id, 'ProductToAddress'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('cruds', 'New'),
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('cruds', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('app\models\ProductToAddress'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'id',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'address_id',
                'value' => ($model->getAddress()->one() ? 
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['//address/index']).' '.
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getAddress()->one()->label, ['//address/view', 'id' => $model->getAddress()->one()->id,]).' '.
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'ProductToAddress'=>['address_id' => $model->address_id]])
                    : 
                    '<span class="label label-warning">?</span>'),
            ],
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'product_id',
                'value' => ($model->getProduct()->one() ? 
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['//product/index']).' '.
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getProduct()->one()->label, ['//product/view', 'id' => $model->getProduct()->one()->id,]).' '.
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'ProductToAddress'=>['product_id' => $model->product_id]])
                    : 
                    '<span class="label label-warning">?</span>'),
            ],
        'quantity',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('cruds', 'Delete'), ['delete', 'id' => $model->id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('cruds', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['app\models\ProductToAddress'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
