<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use app\components\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\Unit $model
 * @var yii\bootstrap\ActiveForm $form
 */

?>

<div class="unit-form">

    <?php $form = ActiveForm::begin([
        'id' => 'Unit',
        'layout' => 'horizontal',
        'enableClientValidation' => false,
    ]); ?>

    <?= Html::hiddenInput('ru', ReturnUrl::getRequestToken()); ?>

    <?= $form->errorSummary($model); ?>

    <?php $this->beginBlock('main'); ?>

    <?= $form->field($model, 'id')->textInput() ?>

    <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
    $form->field($model, 'item_id')->widget(\kartik\select2\Select2::classname(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'item_id',
        'data' => \yii\helpers\ArrayHelper::map(app\models\Item::find()->all(), 'id', 'label'),
        'options' => [
            'placeholder' => Yii::t('app', 'Type to autocomplete'),
            'multiple' => false,
        ]
    ]); ?>

    <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
    $form->field($model, 'package_id')->widget(\kartik\select2\Select2::classname(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'package_id',
        'data' => \yii\helpers\ArrayHelper::map(app\models\Package::find()->all(), 'id', 'id'),
        'options' => [
            'placeholder' => Yii::t('app', 'Type to autocomplete'),
            'multiple' => false,
        ]
    ]); ?>

    <?= $form->field($model, 'quantity')->textInput() ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>


    <?php $this->endBlock(); ?>

    <?= Tabs::widget([
        'encodeLabels' => false,
        'items' => [
            [
                'label' => 'Unit',
                'content' => $this->blocks['main'],
                'active' => true,
            ],
        ],
    ]); ?>
    <?= Html::submitButton('<span class="fa fa-check"></span> ' . ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')), [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
    ]); ?>
    <?php if($model->isNewRecord) echo Html::a('<span class="fa fa-times"></span> ' . Yii::t('app', 'Cancel'), ReturnUrl::getUrl(['index']), ['class' => 'btn btn-default']) ?>

    <?php ActiveForm::end(); ?>

</div>
