<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;
use app\components\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\Unit $model
 */

$this->title = Yii::t('app', 'Unit') . ' ' . $model->id;
$this->params['heading'] = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Units'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->params['heading'];
?>
<div class="unit-view">

    <?= $this->render('_menu', compact('model')); ?>
    <?php $this->beginBlock('app\models\Unit'); ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'item_id',
                'value' => ($model->getItem()->one() ? Html::a($model->getItem()->one()->label, ['//item/view', 'id' => $model->getItem()->one()->id,]) : '<span class="label label-warning">?</span>'),
            ],
            // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'package_id',
                'value' => ($model->getPackage()->one() ? Html::a($model->getPackage()->one()->id, ['//package/view', 'id' => $model->getPackage()->one()->id,]) : '<span class="label label-warning">?</span>'),
            ],
            'quantity',
            'status',
        ],
    ]); ?>

    <?php $this->endBlock(); ?>

    <?= Tabs::widget([
        'id' => 'relation-tabs',
        'encodeLabels' => false,
        'items' => [
            [
                'label' => '<span class="fa fa-asterisk"></span> Unit',
                'content' => $this->blocks['app\models\Unit'],
                'active' => true,
            ],
        ]
    ]);
    ?>

</div>
